version: '3'

services:
  # Django web application
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: gunicorn socotec.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0

  # Celery worker
  worker:
    build:
      context: .
    command: celery -A socotec worker --loglevel=info
    depends_on:
      - web

    environment:
      - DJANGO_DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0

  # Redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
